import {
  defineConfig,
  presetAttributify,
  presetIcons,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

import { presetUni } from '@uni-helper/unocss-preset-uni'
import {
  transformerAttributify,
} from 'unocss-applet'

export default defineConfig({
  presets: [
    presetUni({
      attributify: {
        ignoreAttributes: [
          'color',
          'size',
          'block',
          'mode',
          'custom-class',
          'custom-input-class',
          'active-color',
          'inline',
          'border',
        ],
      },
    }),
    presetIcons({
      scale: 1.2,
      warn: true,
      extraProperties: {
        'display': 'inline-block',
        'vertical-align': 'middle',
      },
    }),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
    transformerAttributify({ // 使得unocss属性支持 color-#00aa44  w-50% (% # {}等默认不支持的字符) 等的关键（H5）
      ignoreAttributes: [ // 使得H5支持属性忽略
        'color',
        'size',
        'block',
        'mode',
        'custom-class',
        'custom-input-class',
        'active-color',
        'inline',
        'border',
      ],
    }),
  ],
  rules: [
    ['wp100', { width: '100%' }],
    ['hp100', { height: '100%' }],
    ['wp50', { width: '50%' }],
    ['hp50', { height: '50%' }],
    [/^wp-([.\d]+)$/, ([_, num]) => ({ width: `${num}%` })],
    [/^hp-([.\d]+)$/, ([_, num]) => ({ height: `${num}%` })],
    [/^fs-([.\d]+)$/, ([_, num]) => ({ 'font-size': `${num}rpx` })],
    [/^fs-([.\d]+)px$/, ([_, num]) => ({ 'font-size': `${num}px` })],
    [/^color-([0-9a-zA-Z]+)$/, ([_, hex]) => ({ color: `#${hex}` })],
    [/^c-([0-9a-zA-Z]+)$/, ([_, hex]) => ({ color: `#${hex}` })],
    [/^bg-([0-9a-zA-Z]+)$/, ([_, hex]) => ({ 'background-color': `#${hex}` })],
    ['bd', { border: '1px solid blue' }],
    ['bd-red', { border: '1px solid red' }],
    ['tc', { 'text-align': 'center' }],
    ['tl', { 'text-align': 'left' }],
    ['tr', { 'text-align': 'right' }],
    ['ma', { margin: '0 auto' }],
    ['oa', { overflow: 'auto' }],
    ['oh', { overflow: 'hidden' }],
    ['oa-y', { 'overflow-y': 'auto' }],
    ['oh-y', { 'overflow-y': 'hidden' }],
    ['oa-x', { 'overflow-x': 'auto' }],
    ['oh-x', { 'overflow-x': 'hidden' }],
    ['fl', { float: 'left' }],
    ['fr', { float: 'right' }],
    ['pr', { position: 'relative' }],
    ['pa', { position: 'absolute' }],
    ['pf', { position: 'fixed' }],
    ['fc', { left: '50%', transform: 'translateX(-50%)' }],
    ['ps', { position: 'sticky' }],
    ['dib', { display: 'inline-block' }],
    ['fb', { 'font-weight': 'bold' }],
    ['fn', { 'font-weight': 'normal' }],
    ['f10', { 'font-size': '20rpx' }],
    ['f12', { 'font-size': '24rpx' }],
    ['f13', { 'font-size': '26rpx' }],
    ['f14', { 'font-size': '28rpx' }],
    ['f16', { 'font-size': '32rpx' }],
    ['f18', { 'font-size': '36rpx' }],
    ['br4', { 'border-radius': '4px' }],
    ['br8', { 'border-radius': '8px' }],
    ['round', { 'border-radius': '50%' }],
    ['color-333', { color: '#333' }],
    ['color-666', { color: '#666' }],
    ['color-999', { color: '#999' }],
    ['color-white', { color: '#fff' }],
    ['color-black', { color: '#5a5a5a' }],
    ['color-red', { color: '#FF1919' }],
    ['color-blue', { color: '#1A66FF' }],
    ['bg-white', { 'background-color': '#fff' }],
    ['bg-black', { 'background-color': '#5a5a5a' }],
    ['bg-red', { 'background-color': '#FF1919' }],
    ['bg-blue', { 'background-color': '#1A66FF' }],
    ['theme-bg', { 'background-color': '#1A66FF' }],
    ['theme-color', { color: '#1A66FF' }],
    ['theme-red', { color: '#FF1919' }],
    ['hide', { color: 'transparent', background: 'transparent' }],
    ['flex-xr', { 'flex-direction': 'row-reverse' }],
    ['flex-y', { 'flex-direction': 'column' }],
    ['flex-bt', { 'justify-content': 'space-between' }],
    ['flex-rd', { 'justify-content': 'space-around' }],
    ['flex-ac', { 'align-items': 'center' }],
    ['flex-cc', { 'justify-content': 'center', 'align-items': 'center' }],
    ['abs-cc', { position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)' }],
    ['x-center', { left: '50%', transform: 'translateX(-50%)' }],
    ['ellipsis', { 'overflow': 'hidden', 'white-space': 'nowrap', 'text-overflow': 'ellipsis', 'word-break': 'break-all' }],
  ],
})
