/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseDataProduct: typeof import('./components/base-data/Product.vue')['default']
    BaseDataService: typeof import('./components/base-data/Service.vue')['default']
    BaseDataStaff: typeof import('./components/base-data/Staff.vue')['default']
    BookList: typeof import('./components/BookList.vue')['default']
    DashboardCard: typeof import('./components/DashboardCard.vue')['default']
    Grids96: typeof import('./components/Grids96.vue')['default']
    GridTagSelect: typeof import('./components/GridTagSelect.vue')['default']
    MsgClock: typeof import('./components/MsgClock.vue')['default']
    MsgRing: typeof import('./components/MsgRing.vue')['default']
    MyButton: typeof import('./components/MyButton.vue')['default']
    MyCell: typeof import('./components/MyCell.vue')['default']
    MyCellGroup: typeof import('./components/MyCellGroup.vue')['default']
    MyNavBar: typeof import('./components/MyNavBar.vue')['default']
    MySquare: typeof import('./components/MySquare.vue')['default']
    MyTabBar: typeof import('./components/MyTabBar.vue')['default']
    StepNav: typeof import('./components/StepNav.vue')['default']
    StripDot: typeof import('./components/StripDot.vue')['default']
    TopSearch: typeof import('./components/TopSearch.vue')['default']
  }
}
