/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DashboardCard: typeof import('./components/DashboardCard.vue')['default']
    GridTagSelect: typeof import('./components/GridTagSelect.vue')['default']
    MsgClock: typeof import('./components/MsgClock.vue')['default']
    MsgRing: typeof import('./components/MsgRing.vue')['default']
    MyCell: typeof import('./components/MyCell.vue')['default']
    MyCellGroup: typeof import('./components/MyCellGroup.vue')['default']
    StepNav: typeof import('./components/StepNav.vue')['default']
    StripDot: typeof import('./components/StripDot.vue')['default']
    TopSearch: typeof import('./components/TopSearch.vue')['default']
  }
}
