/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index" |
       "/pages/tab-business-book" |
       "/pages/tab-business-customer" |
       "/pages/tab-business-dashboard" |
       "/pages/tab-business-my" |
       "/pagesA/billing/billing" |
       "/pagesA/billing/customer-list" |
       "/pagesA/billing/goods-list" |
       "/pagesA/billing/index" |
       "/pagesA/billing/pay-success" |
       "/pagesA/billing/pay" |
       "/pagesA/book/add" |
       "/pagesA/book/detail" |
       "/pagesA/book/submit" |
       "/pagesA/book/time" |
       "/pagesA/booking/d2dTime" |
       "/pagesA/booking/index" |
       "/pagesA/booking/share" |
       "/pagesA/booking/storeTime" |
       "/pagesA/card/list" |
       "/pagesA/card/share" |
       "/pagesA/customer/add" |
       "/pagesA/customer/detail" |
       "/pagesA/customer/index" |
       "/pagesA/dashboard/cash-apply" |
       "/pagesA/dashboard/cashing-records" |
       "/pagesA/dashboard/income-detail" |
       "/pagesA/dashboard/index" |
       "/pagesA/dashboard/pay-ways" |
       "/pagesA/dashboard/store" |
       "/pagesA/dashboard/wallet" |
       "/pagesA/login/index" |
       "/pagesA/login/info" |
       "/pagesA/login/role-select" |
       "/pagesA/msg/detail-expire" |
       "/pagesA/msg/detail-renew" |
       "/pagesA/msg/list" |
       "/pagesA/my/about" |
       "/pagesA/my/index" |
       "/pagesA/my/invite" |
       "/pagesA/my/my-invite" |
       "/pagesA/my/new-store" |
       "/pagesA/my/protocal" |
       "/pagesA/my/qiwei" |
       "/pagesA/my/service" |
       "/pagesA/my/settings" |
       "/pagesA/my/store-info" |
       "/pagesA/my/store" |
       "/pagesA/order/detail" |
       "/pagesA/order/index" |
       "/pagesA/order/refund-detail" |
       "/pagesA/order/refund" |
       "/pagesA/product/add" |
       "/pagesA/product/cat" |
       "/pagesA/product/list" |
       "/pagesA/product/share" |
       "/pagesA/service/add" |
       "/pagesA/service/cat" |
       "/pagesA/service/index" |
       "/pagesA/service/share" |
       "/pagesA/staff/add" |
       "/pagesA/staff/detail" |
       "/pagesA/staff/index" |
       "/pagesA/staff/work-time" |
       "/pagesA/init/steps/done" |
       "/pagesA/init/steps/index" |
       "/pagesA/init/steps/step1" |
       "/pagesA/init/steps/step2" |
       "/pagesA/init/steps/step3-1" |
       "/pagesA/init/steps/step3-2" |
       "/pagesA/init/steps/step3-3" |
       "/pagesA/init/steps/step3" |
       "/pagesA/init/steps/step4" |
       "/pagesA/init/steps/step5" |
       "/pagesB/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/tab-business-dashboard" | "/pages/tab-business-book" | "/pages/tab-business-customer" | "/pages/tab-business-my"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
