/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index" |
       "/pagesA/cats" |
       "/pagesA/prod-servs" |
       "/pagesA/protocol" |
       "/pagesA/rich-edit" |
       "/pagesA/billing/index" |
       "/pagesA/billing/pay-success" |
       "/pagesA/billing/pay" |
       "/pagesA/billing/select-card-billing" |
       "/pagesA/book/add" |
       "/pagesA/book/detail" |
       "/pagesA/book/servs" |
       "/pagesA/book/submit" |
       "/pagesA/book/time" |
       "/pagesA/booking/d2dTime" |
       "/pagesA/booking/index" |
       "/pagesA/booking/storeTime" |
       "/pagesA/card/card-add-chongzhika" |
       "/pagesA/card/card-add-cika" |
       "/pagesA/card/card-add-zhekouka" |
       "/pagesA/card/cus-detail" |
       "/pagesA/card/cus-list" |
       "/pagesA/card/detail" |
       "/pagesA/card/list" |
       "/pagesA/card/make" |
       "/pagesA/card/select-card-common" |
       "/pagesA/card/select-card-multiple" |
       "/pagesA/customer/add" |
       "/pagesA/customer/detail" |
       "/pagesA/customer/list-filter" |
       "/pagesA/customer/list" |
       "/pagesA/customer/points" |
       "/pagesA/dashboard/cash-apply" |
       "/pagesA/dashboard/cash-results" |
       "/pagesA/dashboard/cashing-records" |
       "/pagesA/dashboard/income-detail" |
       "/pagesA/dashboard/pay-ways" |
       "/pagesA/dashboard/store" |
       "/pagesA/dashboard/wallet" |
       "/pagesA/login/index" |
       "/pagesA/login/info" |
       "/pagesA/login/role-select" |
       "/pagesA/msg/detail-expire" |
       "/pagesA/msg/detail-renew" |
       "/pagesA/msg/list" |
       "/pagesA/my/about" |
       "/pagesA/my/feedback" |
       "/pagesA/my/invite" |
       "/pagesA/my/my-invite" |
       "/pagesA/my/new-store" |
       "/pagesA/my/protocal" |
       "/pagesA/my/qiwei" |
       "/pagesA/my/renew" |
       "/pagesA/my/service" |
       "/pagesA/my/settings" |
       "/pagesA/my/store" |
       "/pagesA/order/detail" |
       "/pagesA/order/index" |
       "/pagesA/order/refund-detail" |
       "/pagesA/order/refund" |
       "/pagesA/product/add" |
       "/pagesA/product/list" |
       "/pagesA/service/add" |
       "/pagesA/service/index" |
       "/pagesA/staff/add" |
       "/pagesA/staff/detail" |
       "/pagesA/staff/index" |
       "/pagesA/staff/work-time" |
       "/pagesA/store/list" |
       "/pagesA/tabs/MyTabBar" |
       "/pagesA/tabs/tab-business-book" |
       "/pagesA/tabs/tab-business-customer" |
       "/pagesA/tabs/tab-business-dashboard" |
       "/pagesA/tabs/tab-business-data" |
       "/pagesA/tabs/tab-business-my" |
       "/pagesA/init/steps/done" |
       "/pagesA/init/steps/index" |
       "/pagesA/init/steps/step1" |
       "/pagesA/init/steps/step2" |
       "/pagesA/init/steps/step3-1" |
       "/pagesA/init/steps/step3-2" |
       "/pagesA/init/steps/step3-3" |
       "/pagesA/init/steps/step3" |
       "/pagesA/init/steps/step4" |
       "/pagesA/init/steps/step5" |
       "/pagesA/tabs/components-data/customer-analysis" |
       "/pagesA/tabs/components-data/manage-data" |
       "/pagesA/tabs/components-data/staff-achievements-detail" |
       "/pagesA/tabs/components-data/staff-achievements" |
       "/pagesA/tabs/components-data/staff-statistics" |
       "/pagesB/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
