/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index" |
       "/pages/business/billing/billing" |
       "/pages/business/billing/customer-list" |
       "/pages/business/billing/goods-list" |
       "/pages/business/billing/index" |
       "/pages/business/billing/pay-success" |
       "/pages/business/billing/pay" |
       "/pages/business/book/add" |
       "/pages/business/book/detail" |
       "/pages/business/book/index" |
       "/pages/business/book/list" |
       "/pages/business/book/time" |
       "/pages/business/booking/d2dTime" |
       "/pages/business/booking/index" |
       "/pages/business/booking/share" |
       "/pages/business/booking/storeTime" |
       "/pages/business/card/list" |
       "/pages/business/card/share" |
       "/pages/business/customer/add" |
       "/pages/business/customer/detail" |
       "/pages/business/customer/index" |
       "/pages/business/dashboard/cash-apply" |
       "/pages/business/dashboard/cashing-records" |
       "/pages/business/dashboard/income-detail" |
       "/pages/business/dashboard/index" |
       "/pages/business/dashboard/pay-ways" |
       "/pages/business/dashboard/store" |
       "/pages/business/dashboard/wallet" |
       "/pages/business/login/index" |
       "/pages/business/login/info" |
       "/pages/business/msg/detail-expire" |
       "/pages/business/msg/detail-renew" |
       "/pages/business/msg/list" |
       "/pages/business/my/index" |
       "/pages/business/my/store" |
       "/pages/business/order/detail" |
       "/pages/business/order/index" |
       "/pages/business/product/add" |
       "/pages/business/product/cat" |
       "/pages/business/product/list" |
       "/pages/business/product/share" |
       "/pages/business/service/add" |
       "/pages/business/service/cat" |
       "/pages/business/service/index" |
       "/pages/business/service/share" |
       "/pages/business/staff/add" |
       "/pages/business/staff/detail" |
       "/pages/business/staff/list" |
       "/pages/business/staff/work-time" |
       "/pages/business/init/steps/done" |
       "/pages/business/init/steps/index" |
       "/pages/business/init/steps/step1" |
       "/pages/business/init/steps/step2" |
       "/pages/business/init/steps/step3-1" |
       "/pages/business/init/steps/step3-2" |
       "/pages/business/init/steps/step3-3" |
       "/pages/business/init/steps/step3" |
       "/pages/business/init/steps/step4" |
       "/pages/business/init/steps/step5" |
       "/pagesA/index" |
       "/pagesB/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/business/dashboard/index" | "/pages/business/booking/index" | "/pages/business/customer/index" | "/pages/business/my/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
